FROM node:16
WORKDIR /app
COPY ./server/package.json ./package.json
COPY ./server/server.js ./server.js
COPY ./server/messageModel.js ./messageModel.js 
COPY ./server/roomModel.js ./roomModel.js
COPY ./server/userModel.js ./userModel.js
RUN yarn install 
LABEL developer=saseovh
EXPOSE 9000
CMD ["node", "server.js"]
# docker build . -f Dockerfile.node  -t saseovh/slackclone-be:1
